version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/loan-application
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/start_pm2.sh
      timeout: 300
