version: 0.2

env:
  parameter-store:
    NEXTAUTH_URL: /CodeBuild/NEXTAUTH_SECRET
    DATABASE_URL: /CodeBuild/DATABASE_URL
    NEXTAUTH_SECRET: /CodeBuild/NEXTAUTH_SECRET

phases:
  install:
    commands:
      - echo Installing dependency...
      - npm install -g next
      - yarn
  pre_build:
    commands:
      - printenv > .env 
      - cat .env 
  build:
    commands:
      - echo Compiling the Node.js code
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'