import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import Signin from './signIn'



const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>OcktankCU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Signin></Signin>
        
      </main>

    </div>
  )
}

export default Home
