import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import Signin from './signIn'
import { GetServerSideProps } from "next";
import { InferGetServerSidePropsType } from "next";



export const getServerSideProps: GetServerSideProps = async () => {
    const instanceId = await fetch("http://169.254.169.254/latest/meta-data/instance-id")
    console.log(instanceId)
    return {
      props: {
        instanceId: instanceId,
      }
    }
};

const Home: NextPage = ({
  instanceId,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <div>
      <Head>
        <title>OcktankCU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Signin></Signin>
        {instanceId ? <p>{instanceId}</p> : <></>}
      </main>

    </div>
  )
}

export default Home
